### ISSUE TITLE
Training details of STAR

### ISSUE THREAD

**Issue by HalvesChen** [krennic999/STAR#5]
Hi, I want to know about training details of STAR, such as data scale, training duration, and batch size.

**Comment by HalvesChen** [comment]
One more question, how do you calculate the clip-score on the MJHQ30K dataset? I found that clip couldn't handle the long captions.

**Comment by krennic999** [comment]
About training duration and batch size, you can refer to https://github.com/krennic999/STAR/issues/2#issuecomment-2198149892, the data scale is about 10M high-quality dataset😂, possibly a larger scale can achieve a more stable result.

**Comment by krennic999** [comment]
🤔 For clip-score, the default setting is to truncate overly long prompts...
Similar to https://github.com/THUDM/ImageReward, we set text = clip.tokenize(prompt, truncate=True), and use ViT-L/14 as backbone.
But what you said is indeed an important issue, we will look for more reasonable indicators to evaluate the text-image consistency.

**Comment by HalvesChen** [comment]
Thank you for your reply, it is very helpful. Looking forward to open source.
