### ISSUE TITLE
 Evaluate FID Settings

### ISSUE THREAD

**Issue by HalvesChen** [krennic999/STAR#7]
Hi, I'm interested in the FID review settings, such as the results in this [image](https://github.com/krennic999/STAR/issues/1#issuecomment-2205847780). Do you pre-resize the original image to 256*256 for the 256 resolution evaluation? And are you using the clean-fid library to calculate the FID or some other third-party library?

**Comment by krennic999** [comment]
Yes, we reshape all images to 512 for evaluation, and we use pytorch-fid to calculate.

**Comment by HalvesChen** [comment]
Got it! I initially got a very bad FID when using clean-fid at a resolution of 1024, and I struggled with it for quite some time.

**Comment by HalvesChen** [comment]
> Yes, we reshape all images to 512 for evaluation, and we use pytorch-fid to calculate.

Hi, I would like to confirm the evaluation method of the last column res=256 in your result table. Do you also resize the dataset images to 512*512 and then calculate the FID with the generated  256*256 images?

**Comment by krennic999** [comment]
We reshape reference images to 256 reso to evaluate FID under 256 cases, to match the 256 generated image size
